apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter-hub
  name: jupyter-hub-svc
  namespace: aihub-portal
spec:
  ports:
  - nodePort: 12000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jupyter-hub
  type: NodePort
